### ISSUE TITLE
New account generation with perms assingment

### ISSUE THREAD

**Issue by dsanchezseco** [monax/legacy-db.js#48]
Right now the account generation must be done in two steps. Send coins to an address and then through the CLI give that account the right perms(right now this is also disabled).

It would be awesome to have a JS function to perform this. Something like `GenerateAccount(perms)` that gives you back the account's public and private keys and performs the "mintx set perms" on the fly to add accounts to an existing and running chain.

**Comment by zramsay** [comment]
@dsanchezseco this feature will be added to the platform roadmap and will be offered by eris-db/client in conjunction with https://github.com/eris-ltd/eris/issues/1008

**Comment by NodeGuy** [comment]
Agreed, we'll improve this in the new API.

**Comment by dsanchezseco** [comment]
Thank guys! Looking forward to see this working. This will bring Eris to a whole new level.

**Comment by NodeGuy** [comment]
This has been de-prioritized.

**Comment by dsanchezseco** [comment]
Is this request going to be implemented in the burrow.js library instead?

**Comment by NodeGuy** [comment]
Not for the foreseeable future.
